{
 "title": "Witnet Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outbound Per Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Peer_Number_witnet_node_1", "legendFormat": "N1 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_2", "legendFormat": "N2 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_3", "legendFormat": "N3 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_4", "legendFormat": "N4 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_5", "legendFormat": "N5 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_6", "legendFormat": "N6 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_7", "legendFormat": "N7 {{instance}}" },
    { "expr": "Peer_Number_witnet_node_8", "legendFormat": "N8 {{instance}}" }
   ]
  },
  {
   "title": "Reputation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Reputation_witnet_node_1", "legendFormat": "N1 {{instance}}" },
    { "expr": "Reputation_witnet_node_2", "legendFormat": "N2 {{instance}}" },
    { "expr": "Reputation_witnet_node_3", "legendFormat": "N3 {{instance}}" },
    { "expr": "Reputation_witnet_node_4", "legendFormat": "N4 {{instance}}" },
    { "expr": "Reputation_witnet_node_5", "legendFormat": "N5 {{instance}}" },
    { "expr": "Reputation_witnet_node_6", "legendFormat": "N6 {{instance}}" },
    { "expr": "Reputation_witnet_node_7", "legendFormat": "N7 {{instance}}" },
    { "expr": "Reputation_witnet_node_8", "legendFormat": "N8 {{instance}}" }
   ]
  },
  {
   "title": "Blocks In Blockchain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blocks_in_blockchain_witnet_node_1",
     "legendFormat": "N1 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_2",
     "legendFormat": "N2 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_3",
     "legendFormat": "N3 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_4",
     "legendFormat": "N4 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_5",
     "legendFormat": "N5 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_6",
     "legendFormat": "N6 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_7",
     "legendFormat": "N7 {{instance}}"
    },
    {
     "expr": "Blocks_in_blockchain_witnet_node_8",
     "legendFormat": "N8 {{instance}}"
    }
   ]
  },
  {
   "title": "Balance Per Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Balance_witnet_node_1" },
    { "expr": "Balance_witnet_node_2" },
    { "expr": "Balance_witnet_node_3" },
    { "expr": "Balance_witnet_node_4" },
    { "expr": "Balance_witnet_node_5" },
    { "expr": "Balance_witnet_node_6" },
    { "expr": "Balance_witnet_node_7" },
    { "expr": "Balance_witnet_node_8" }
   ]
  },
  {
   "title": "Eligibility",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "Eligibility_Percentage_witnet_node_1",
       "legendFormat": "N1 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_2",
       "legendFormat": "N2 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_3",
       "legendFormat": "N3 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_4",
       "legendFormat": "N4 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_5",
       "legendFormat": "N5 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_6",
       "legendFormat": "N6 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_7",
       "legendFormat": "N7 {{instance}}"
      },
      {
       "expr": "Eligibility_Percentage_witnet_node_8",
       "legendFormat": "N8 {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Reputation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 11 },
     "targets": [
      { "expr": "Reputation_witnet_node_1", "legendFormat": "N1 {{instance}}" },
      { "expr": "Reputation_witnet_node_2", "legendFormat": "N2 {{instance}}" },
      { "expr": "Reputation_witnet_node_3", "legendFormat": "N3 {{instance}}" },
      { "expr": "Reputation_witnet_node_4", "legendFormat": "N4 {{instance}}" },
      { "expr": "Reputation_witnet_node_5", "legendFormat": "N5 {{instance}}" },
      { "expr": "Reputation_witnet_node_6", "legendFormat": "N6 {{instance}}" },
      { "expr": "Reputation_witnet_node_7", "legendFormat": "N7 {{instance}}" },
      { "expr": "Reputation_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    },
    {
     "title": "Node 1",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_1", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 2",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_2", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 3",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_3", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 4",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_4", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 5",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_5", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 6",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_6", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 7",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_7", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node 8",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Reputation_witnet_node_8", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Proposed Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proposed Blocks Node 1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_1", "legendFormat": "N1 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 2",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_2", "legendFormat": "N2 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_3", "legendFormat": "N3 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_4", "legendFormat": "N4 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 5",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_5", "legendFormat": "N5 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 6",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_6", "legendFormat": "N6 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 7",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_7", "legendFormat": "N7 {{instance}}" }
     ]
    },
    {
     "title": "Proposed Blocks Node 8",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
     "targets": [
      { "expr": "Proposed_blocks_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Balances",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "targets": [
      { "expr": "Balance_witnet_node_1", "legendFormat": "N1 {{instance}}" },
      { "expr": "Balance_witnet_node_2", "legendFormat": "N2 {{instance}}" },
      { "expr": "Balance_witnet_node_3", "legendFormat": "N3 {{instance}}" },
      { "expr": "Balance_witnet_node_4", "legendFormat": "N4 {{instance}}" },
      { "expr": "Balance_witnet_node_5", "legendFormat": "N5 {{instance}}" },
      { "expr": "Balance_witnet_node_6", "legendFormat": "N6 {{instance}}" },
      { "expr": "Balance_witnet_node_7", "legendFormat": "N7 {{instance}}" },
      { "expr": "Balance_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound Peers",
     "type": "stat",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Peer_Number_witnet_node_1", "legendFormat": "N1 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_2", "legendFormat": "N2 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_3", "legendFormat": "N3 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_4", "legendFormat": "N4 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_5", "legendFormat": "N5 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_6", "legendFormat": "N6 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_7", "legendFormat": "N7 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    },
    {
     "title": "Outbound Peers",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
     "targets": [
      { "expr": "Peer_Number_witnet_node_1", "legendFormat": "N1 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_2", "legendFormat": "N2 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_3", "legendFormat": "N3 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_4", "legendFormat": "N4 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_5", "legendFormat": "N5 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_6", "legendFormat": "N6 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_7", "legendFormat": "N7 {{instance}}" },
      { "expr": "Peer_Number_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slashed Commits N1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_1", "legendFormat": "N1 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N2",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_2", "legendFormat": "N2 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N3",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_3", "legendFormat": "N3 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_4", "legendFormat": "N4 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N5",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_5", "legendFormat": "N5 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N6",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_6", "legendFormat": "N6 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N7",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_7", "legendFormat": "N7 {{instance}}" }
     ]
    },
    {
     "title": "Slashed Commits N8",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
     "targets": [
      { "expr": "Slashed_commits_witnet_node_8", "legendFormat": "N8 {{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Blocks in Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes 1 to 4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "Blocks_in_blockchain_witnet_node_1",
       "legendFormat": "N1 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_2",
       "legendFormat": "N2 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_3",
       "legendFormat": "N3 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_4",
       "legendFormat": "N4 {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes 1 to 4",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Blocks_in_blockchain_witnet_node_1",
       "legendFormat": "N1 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_2",
       "legendFormat": "N2 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_3",
       "legendFormat": "N3 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_4",
       "legendFormat": "N4 {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes 5 to 8",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "Blocks_in_blockchain_witnet_node_5",
       "legendFormat": "N5 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_6",
       "legendFormat": "N6 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_7",
       "legendFormat": "N7 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_8",
       "legendFormat": "N8 {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes 5 to 8",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Blocks_in_blockchain_witnet_node_5",
       "legendFormat": "N5 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_6",
       "legendFormat": "N6 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_7",
       "legendFormat": "N7 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_8",
       "legendFormat": "N8 {{instance}}"
      }
     ]
    },
    {
     "title": "All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "Blocks_in_blockchain_witnet_node_1",
       "legendFormat": "N1 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_2",
       "legendFormat": "N2 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_3",
       "legendFormat": "N3 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_4",
       "legendFormat": "N4 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_5",
       "legendFormat": "N5 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_6",
       "legendFormat": "N6 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_7",
       "legendFormat": "N7 {{instance}}"
      },
      {
       "expr": "Blocks_in_blockchain_witnet_node_8",
       "legendFormat": "N8 {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}