name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Project Version
      run: VERSION=$(python3 setup.py --version)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prometheus_wit_client:$VERSION
    - name: Push the Docker image
      run: docker push carequinha/prometheus_wit_client:$VERSION
