name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.7.5
    - name: Get Project Version
      run: |
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV
        echo ${{ env.VERSION }}
    - name: Check if image version already exists
      run: |
        echo "DOCKER_IMAGE_ALREADY_PUSHED=$(docker manifest inspect carequinha/prometheus_wit_client:${{ env.VERSION }} > /dev/null; echo $?)" >> $GITHUB_ENV
        echo ${{ env.DOCKER_IMAGE_ALREADY_PUSHED }}
    - name: Build the Docker image
      if: ${{ env.DOCKER_IMAGE_ALREADY_PUSHED != 0 }}
      run: docker build . --file Dockerfile --tag carequinha/prometheus_wit_client:${{ env.VERSION }} --tag carequinha/prometheus_wit_client:latest
    - name: Push the Docker image
      if: ${{ env.DOCKER_IMAGE_ALREADY_PUSHED != 0 }}
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} docker.io
        docker push carequinha/prometheus_wit_client:${{ env.VERSION }}
        fi
