name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.7.5
    - name: Get Project Version
      env:
        VERSION: ${{python3 setup.py --version}}
      run: echo VERSION
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prometheus_wit_client:$VERSION
    - name: Push the Docker image
      run: docker push carequinha/prometheus_wit_client:$VERSION
