name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version: 3.7.5
    - name: Get Project Version
      run: |
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV
        echo env.VERSION
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag carequinha/prometheus_wit_client:${{ env.VERSION }} --tag carequinha/prometheus_wit_client:latest
    - name: Push the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrects.DOCKER_PASSWORD}} docker.io
        docker push carequinha/prometheus_wit_client:${{ env.VERSION }}
